services:

  mysql-memory:
    image: '${MYSQL_MEMORY_IMAGE:-mysql:8.4}'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_MEMORY_ROOT_PASSWORD:-}'
      MYSQL_DATABASE: '${MYSQL_MEMORY_DATABASE:-db}'
      MYSQL_USER: '${MYSQL_MEMORY_USER:-db}'
      MYSQL_PASSWORD: '${MYSQL_MEMORY_PASSWORD:-}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '127.0.0.1:${MYSQL_MEMORY_EXPOSE_PORT:-}:3306'
    expose:
      - 3307
    tmpfs:
      - /var/lib/mysql
    volumes:
#      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/shared:/shared
      - ./build/mysql/configuration/my.cnf:/etc/mysql/my.cnf
      - ./build/mysql/profile.d:/etc/profile.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_MEMORY_PASSWORD:-}"]
      retries: 3
      timeout: 5s
