services:

  node:
    build:
      context: './build/node'
      args:
        - NODE_IMAGE=${NODE_IMAGE:-node:24-bookworm}
    ports:
      - "${NGINX_EXPOSE_TO_IP:-127.0.0.1}:${NODE_NPM_RUN_DEV_PORT:-}:5173"
    volumes:
      - ${NODE_VOLUME_SOURCE:-../}:/app/
      - ./volumes/shared:/shared
      - ./build/node/profile.d:/etc/profile.d
