services:

  searxng:
    image: '${SEARXNG_IMAGE:-searxng/searxng:latest}'
    ports:
      - "${SEARXNG_EXPOSE_TO_IP:-127.0.0.1}:${SEARXNG_PORT:-8080}:8080"
    environment:
      BASE_URL: "http://localhost:${SEARXNG_PORT:-8080}/"
      SEARXNG_REDIS_URL: "redis://valkey:6379/0"
      SEARXNG_STATIC_USE_HASH: "true"
    volumes:
      - ./volumes/searxng:/etc/searxng
    restart: unless-stopped
