services:

  valkey:
    image: '${VALKEY_IMAGE:-docker.io/valkey/valkey:8-alpine}'
    command: valkey-server --save 30 1 --loglevel warning
    expose:
      - 6379
    volumes:
      - ./volumes/valkey:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped
